import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Product } from '../db/schema';

interface SalesReportData {
    dateRange: string;
    totalSales: number;
    totalTransactions: number;
    averageOrderValue: number;
    topProducts?: { name: string; quantity: number; revenue: number }[];
}

interface InventoryReportData {
    products: Product[];
    totalValue: number;
    lowStockCount: number;
}

/**
 * PDF Export Service for RetailCore Reports
 */
export const pdfExport = {
    /**
     * Export Sales Report as PDF
     */
    salesReport: (data: SalesReportData, fileName = 'sales-report.pdf') => {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();

        // Header
        doc.setFontSize(20);
        doc.setTextColor(59, 130, 246); // Primary blue
        doc.text('RetailCore', 14, 20);

        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text('Sales Report', 14, 30);

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Period: ${data.dateRange}`, 14, 38);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 44);

        // Summary Box
        doc.setDrawColor(200, 200, 200);
        doc.setFillColor(249, 250, 251);
        doc.roundedRect(14, 52, pageWidth - 28, 35, 3, 3, 'FD');

        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);

        const col1X = 24;
        const col2X = pageWidth / 2 + 10;

        doc.text('Total Sales:', col1X, 65);
        doc.setFont('helvetica', 'bold');
        doc.text(`Rs. ${data.totalSales.toLocaleString()}`, col1X + 40, 65);

        doc.setFont('helvetica', 'normal');
        doc.text('Transactions:', col1X, 75);
        doc.setFont('helvetica', 'bold');
        doc.text(`${data.totalTransactions}`, col1X + 40, 75);

        doc.setFont('helvetica', 'normal');
        doc.text('Avg Order:', col2X, 65);
        doc.setFont('helvetica', 'bold');
        doc.text(`Rs. ${data.averageOrderValue.toLocaleString()}`, col2X + 35, 65);

        // Top Products Table
        if (data.topProducts && data.topProducts.length > 0) {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(14);
            doc.setTextColor(0, 0, 0);
            doc.text('Top Selling Products', 14, 100);

            autoTable(doc, {
                startY: 105,
                head: [['Product', 'Qty Sold', 'Revenue']],
                body: data.topProducts.map(p => [
                    p.name,
                    p.quantity.toString(),
                    `Rs. ${p.revenue.toLocaleString()}`
                ]),
                theme: 'striped',
                headStyles: { fillColor: [59, 130, 246] },
            });
        }

        // Footer
        const pageCount = doc.internal.pages.length - 1;
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by RetailCore POS', 14, doc.internal.pageSize.getHeight() - 10);
        doc.text(`Page 1 of ${pageCount}`, pageWidth - 30, doc.internal.pageSize.getHeight() - 10);

        doc.save(fileName);
    },

    /**
     * Export Inventory Report as PDF
     */
    inventoryReport: (data: InventoryReportData, fileName = 'inventory-report.pdf') => {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();

        // Header
        doc.setFontSize(20);
        doc.setTextColor(59, 130, 246);
        doc.text('RetailCore', 14, 20);

        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text('Inventory Report', 14, 30);

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 38);

        // Summary
        doc.setDrawColor(200, 200, 200);
        doc.setFillColor(249, 250, 251);
        doc.roundedRect(14, 45, pageWidth - 28, 25, 3, 3, 'FD');

        doc.setFontSize(11);
        doc.setTextColor(0, 0, 0);
        doc.text(`Total Products: ${data.products.length}`, 24, 57);
        doc.text(`Total Value: Rs. ${data.totalValue.toLocaleString()}`, 90, 57);
        doc.text(`Low Stock: ${data.lowStockCount}`, 170, 57);

        // Products Table
        autoTable(doc, {
            startY: 78,
            head: [['SKU', 'Product', 'Qty', 'Price', 'Value']],
            body: data.products.map(p => [
                p.sku || '-',
                p.name.substring(0, 25),
                p.quantity.toString(),
                `Rs. ${p.selling_price.toLocaleString()}`,
                `Rs. ${(p.quantity * p.selling_price).toLocaleString()}`
            ]),
            theme: 'striped',
            headStyles: { fillColor: [16, 185, 129] }, // Green
            columnStyles: {
                0: { cellWidth: 25 },
                1: { cellWidth: 60 },
                2: { cellWidth: 20 },
                3: { cellWidth: 35 },
                4: { cellWidth: 35 },
            },
        });

        doc.save(fileName);
    },

    /**
     * Export Low Stock Alert Report
     */
    lowStockReport: (products: Product[], fileName = 'low-stock-report.pdf') => {
        const lowStock = products.filter(p => p.quantity <= p.min_stock_level);

        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();

        // Header
        doc.setFontSize(20);
        doc.setTextColor(245, 158, 11); // Amber
        doc.text('⚠ Low Stock Alert', 14, 20);

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`${lowStock.length} items need attention`, 14, 28);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 60, 28);

        if (lowStock.length === 0) {
            doc.setFontSize(14);
            doc.setTextColor(16, 185, 129);
            doc.text('✓ All products are well stocked!', 14, 50);
        } else {
            autoTable(doc, {
                startY: 38,
                head: [['Product', 'Current', 'Minimum', 'Status']],
                body: lowStock.map(p => [
                    p.name,
                    p.quantity.toString(),
                    p.min_stock_level.toString(),
                    p.quantity === 0 ? 'OUT OF STOCK' : 'LOW STOCK'
                ]),
                theme: 'striped',
                headStyles: { fillColor: [245, 158, 11] },
                bodyStyles: { fontSize: 10 },
                didParseCell: (data) => {
                    if (data.column.index === 3 && data.section === 'body') {
                        if (data.cell.raw === 'OUT OF STOCK') {
                            data.cell.styles.textColor = [239, 68, 68];
                            data.cell.styles.fontStyle = 'bold';
                        } else {
                            data.cell.styles.textColor = [245, 158, 11];
                        }
                    }
                },
            });
        }

        doc.save(fileName);
    },
};

export default pdfExport;
